ARGS:
  dataset: scannet
  model_name: votenet
  task: train

  tag: 
  gpu: 0
  batch_size: 8
  verbose: 10

  epoch: 20
  val_step: 2000
  lr: 0.001
  wd: 0.00001
  num_points: 40000
  num_proposals: 256
  num_locals: -1
  num_scenes: -1

  num_graph_steps: 0
  seed: 42
  criterion: cider #[choices: bleu-1, bleu-2, bleu-3, bleu-4, cider, rouge, meteor, sum]

  query_mode: center
  graph_mode: edge_conv
  graph_aggr: add
  
  no_height: False
  no_augment: False
  no_detection: False
  no_caption: False
  use_tf: True
  use_color: True
  use_normal: False
  use_multiview: True
  use_topdown: False
  use_relation: False
  use_new: False
  use_orientation: False
  use_distance: False

  use_pretrained: 
  use_checkpoint:
  debug: False
  report_ap: False